import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/app/providers';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

import { Anonymous_Pro } from 'next/font/google';

const anonymousPro = Anonymous_Pro({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'], // Available weights for Anonymous Pro
  style: ['normal', 'italic'], // Include if you need italic styles
  display: 'swap',
  variable: '--font-anonymous-pro',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" className={anonymousPro.className}>
        <body>{children}</body>
      </html>
    </Providers>
  );
}
